package com.txuritan.patch.main;

import java.util.Arrays;

public class Info
{
	public static final String MODID = "patch";
	public static final String NAME = "Patch";
	public static final String DES = "The core of all my mods.";
    public static final String DEP = "before:YuTanLib";
    public static final String URL = "http://txuritan.github.io/";
    public static final String VER = "1.6.4-A-0.0.4-0.5";
    
    /*  --Version Setup--
     * Version "1.6.4-A-1.2.3-4.5"
     * 1.6.4 <Minecraft Version>
     * A <Build State "'A' Alpha, 'B' Beta, 'O' Omega">
     * 1 <Full Release Omega Build Number>
     * 2 <Full Release Beta Build Number>
     * 3 <Full Release Alpha Build Number>
     * 4 <Bug Fix Build Number>
     * 5 <Bug Fix Build Number>
     */
    
    public static final String CLIENT = "com.txuritan.patch.main.ref.proxy.ProxyClient";
	public static final String COMMON = "com.txuritan.patch.main.ref.proxy.ProxyCommon";
	
	public static void metadata()
	{
		Patch.metadata.modId = MODID;
		Patch.metadata.name = NAME;
		Patch.metadata.description = DES;
		Patch.metadata.url = URL;
		Patch.metadata.version = VER;
		Patch.metadata.authorList = Arrays.asList(new String[] { "Txuritan" });
		Patch.metadata.credits = "Please visit the website.";
		Patch.metadata.autogenerated = false;
	}
}
